// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjWebsiteB.Models;

public partial class TAttractionComment
{
    public int FCommentId { get; set; }

    public int? FAttractionId { get; set; }

    public int? FUserId { get; set; }

    public int? FRating { get; set; }

    public string FComment { get; set; }

    public DateTime? FCreatedDate { get; set; }

    public virtual TAttraction FAttraction { get; set; }

    public virtual TUser FUser { get; set; }
}