// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjWebsiteB.Models;

public partial class TAttractionImage
{
    public int FAttractionImageId { get; set; }

    public int? FAttractionId { get; set; }

    public byte[] FImage { get; set; }

    public virtual TAttraction FAttraction { get; set; }
}