// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjWebsiteB.Models;

public partial class TAttraction
{
    public int FAttractionId { get; set; }

    public string FAttractionName { get; set; }

    public string FDescription { get; set; }

    public string FAddress { get; set; }

    public string FPhoneNumber { get; set; }

    public TimeOnly? FOpeningTime { get; set; }

    public TimeOnly? FClosingTime { get; set; }

    public string FWebsiteUrl { get; set; }

    public string FLongitude { get; set; }

    public string FLatitude { get; set; }

    public string FRegion { get; set; }

    public int? FCategoryId { get; set; }

    public DateTime? FCreatedDate { get; set; }

    public DateTime? FUpdatedDate { get; set; }

    public string FStatus { get; set; }

    public string FTrafficInformation { get; set; }

    public virtual TAttractionCategory FCategory { get; set; }

    public virtual ICollection<TAttractionComment> TAttractionComments { get; set; } = new List<TAttractionComment>();

    public virtual ICollection<TAttractionImage> TAttractionImages { get; set; } = new List<TAttractionImage>();

    public virtual ICollection<TAttractionTicket> TAttractionTickets { get; set; } = new List<TAttractionTicket>();
}