// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjWebsiteB.Models;

public partial class TAttractionTicketOrder
{
    public int FAttractionTicketOrderId { get; set; }

    public int FBuyerId { get; set; }

    public int FAttractionTicketId { get; set; }

    public int? FOrderQty { get; set; }

    public decimal? FUnitPrice { get; set; }

    public DateTime? FCreatedDate { get; set; }

    public virtual TAttractionTicket FAttractionTicket { get; set; }

    public virtual TUser FBuyer { get; set; }
}