// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjWebsiteB.Models;

public partial class TAttractionCategory
{
    public int FAttractionCategoryId { get; set; }

    public string FAttractionCategoryName { get; set; }

    public string FDescription { get; set; }

    public DateTime? FCreateDate { get; set; }

    public virtual ICollection<TAttraction> TAttractions { get; set; } = new List<TAttraction>();
}