// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjWebsiteB.Models;

public partial class TEvent
{
    public int FEventId { get; set; }

    public int? FUserId { get; set; }

    public string FEventName { get; set; }

    public string FEventDescription { get; set; }

    public string FEventStartDate { get; set; }

    public string FEventEndDate { get; set; }

    public string FEventLocation { get; set; }

    public DateTime? FEventCreatedDate { get; set; }

    public DateTime? FEventUpdatedDate { get; set; }

    public decimal? FEventActivityfee { get; set; }

    public string FEventUrl { get; set; }

    public int? FEventMaxParticipants { get; set; }

    public int? FEventCurrentParticipants { get; set; }

    public bool? FEventIsActive { get; set; }

    public virtual TUser FUser { get; set; }

    public virtual ICollection<TEventCategoryMapping> TEventCategoryMappings { get; set; } = new List<TEventCategoryMapping>();

    public virtual ICollection<TEventImage> TEventImages { get; set; } = new List<TEventImage>();

    public virtual ICollection<TEventRegistrationForm> TEventRegistrationForms { get; set; } = new List<TEventRegistrationForm>();
}