// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjWebsiteB.Models;

public partial class TEventCategory
{
    public int FEventCategoryId { get; set; }

    public string FEventCategoryName { get; set; }

    public string FEventDescriptionn { get; set; }

    public DateTime? FEventCreatedDate { get; set; }

    public virtual ICollection<TEventCategoryMapping> TEventCategoryMappings { get; set; } = new List<TEventCategoryMapping>();
}