// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjWebsiteB.Models;

public partial class TEventImage
{
    public int FEventImageId { get; set; }

    public int? FEventId { get; set; }

    public byte[] FEventImage { get; set; }

    public virtual TEvent FEvent { get; set; }
}