// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjWebsiteB.Models;

public partial class TEventRegistrationForm
{
    public int FEventRegistrationFormId { get; set; }

    public int? FEventId { get; set; }

    public int? FUserId { get; set; }

    public int? FEventRegistrationCount { get; set; }

    public string FEventContact { get; set; }

    public string FEventContactPhone { get; set; }

    public DateTime? FEregistrationDate { get; set; }

    public string FRegistrationStatus { get; set; }

    public DateTime? FPaymentDate { get; set; }

    public decimal? FPaymentAmount { get; set; }

    public string FPaymentStatus { get; set; }

    public string FPaymentMethod { get; set; }

    public DateTime? FCancellationDate { get; set; }

    public string FCancellationReason { get; set; }

    public virtual TEvent FEvent { get; set; }

    public virtual TUser FUser { get; set; }

    public virtual ICollection<TOrdersDetail> TOrdersDetails { get; set; } = new List<TOrdersDetail>();
}