// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjWebsiteB.Models;

public partial class TEventCategoryMapping
{
    public int FEventCategoryMappingId { get; set; }

    public int? FEventCategoryId { get; set; }

    public int? FEventId { get; set; }

    public virtual TEvent FEvent { get; set; }

    public virtual TEventCategory FEventCategory { get; set; }
}