// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjWebsiteB.Models;

public partial class TOrderStatus
{
    public int FOrderStatusId { get; set; }

    public string FStatusName { get; set; }

    public virtual ICollection<TOrder> TOrderFOrderStatuses { get; set; } = new List<TOrder>();

    public virtual ICollection<TOrder> TOrderFStatuses { get; set; } = new List<TOrder>();
}