// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjWebsiteB.Models;

public partial class TPostCategory
{
    public int FCategoryId { get; set; }

    public int? FUserId { get; set; }

    public string FName { get; set; }

    public virtual TUser FUser { get; set; }

    public virtual ICollection<TPost> TPosts { get; set; } = new List<TPost>();
}