// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjWebsiteB.Models;

public partial class TPostTag
{
    public int FTagId { get; set; }

    public string FTagName { get; set; }

    public virtual ICollection<TPostAndTag> TPostAndTags { get; set; } = new List<TPostAndTag>();
}