// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjWebsiteB.Models;

public partial class TProduct
{
    public int FProductId { get; set; }

    public int? FUserId { get; set; }

    public int? FProductCategoryId { get; set; }

    public string FProductName { get; set; }

    public string FProductDescription { get; set; }

    public decimal? FProductPrice { get; set; }

    public bool? FIsOnSales { get; set; }

    public DateTime? FProductDateAdd { get; set; }

    public DateTime? FProductUpdated { get; set; }

    public int? FStock { get; set; }

    public virtual TProductCategory FProductCategory { get; set; }

    public virtual TUser FUser { get; set; }

    public virtual ICollection<TOrdersDetail> TOrdersDetails { get; set; } = new List<TOrdersDetail>();

    public virtual ICollection<TProductImage> TProductImages { get; set; } = new List<TProductImage>();
}