// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjWebsiteB.Models;

public partial class TProductImage
{
    public int FProductImageId { get; set; }

    public int? FProductId { get; set; }

    public byte[] FImage { get; set; }

    public virtual TProduct FProduct { get; set; }
}