// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjWebsiteB.Models;

public partial class TUser
{
    public int FUserId { get; set; }

    public int? FUserRankId { get; set; }

    public string FUserName { get; set; }

    public byte[] FUserImage { get; set; }

    public string FUserNickName { get; set; }

    public string FUserSex { get; set; }

    public DateTime? FUserBirthday { get; set; }

    public string FUserPhone { get; set; }

    public string FUserEmail { get; set; }

    public string FUserAddress { get; set; }

    public DateTime? FUserComeDate { get; set; }

    public string FUserPassword { get; set; }

    public bool? FUserNotify { get; set; }

    public bool? FUserOnLine { get; set; }

    public virtual ICollection<TAttractionComment> TAttractionComments { get; set; } = new List<TAttractionComment>();

    public virtual ICollection<TAttractionTicketOrder> TAttractionTicketOrders { get; set; } = new List<TAttractionTicketOrder>();

    public virtual ICollection<TEventRegistrationForm> TEventRegistrationForms { get; set; } = new List<TEventRegistrationForm>();

    public virtual ICollection<TEvent> TEvents { get; set; } = new List<TEvent>();

    public virtual ICollection<TOrder> TOrders { get; set; } = new List<TOrder>();

    public virtual ICollection<TPostCategory> TPostCategories { get; set; } = new List<TPostCategory>();

    public virtual ICollection<TPost> TPosts { get; set; } = new List<TPost>();

    public virtual ICollection<TProduct> TProducts { get; set; } = new List<TProduct>();
}